#Import the necessary methods from tweepy library
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API 
access_token = "3904981821-aG4hTxXMrdFtwMtPh9h3s1KM3I7ZxeZzkHWlX1F"
access_token_secret = "ka1caG2BWXRP1vNCd34WBA3e7nn0b2jnXQQ0EKoMn54ck"
consumer_key = "jvngcbJOm7YFCmMiGDIjqfvYd"
consumer_secret = "FBTYg8GEvENy6RI6CnMPGVkbZC5dwsEQIAUwohOHRRZ4Zn0pYM"


#This is a basic listener that just prints received tweets to stdout.
class StdOutListener(StreamListener):

    def on_data(self, data):
        print data
        return True

    def on_error(self, status):
        print status


if __name__ == '__main__':

    #This handles Twitter authetification and the connection to Twitter Streaming API
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l)

    #This line filter Twitter Streams to capture data by the keywords: 'python', 'javascript', 'ruby'
    stream.filter(track=['Assassination',
'Attack',
'Domestic Security',
'Drill',
'Exercise',
'Cops',
'Law Enforcement',
'Authorities',
'Disaster Management',
'DNDO',
'National preparedness',
'Mitigation',
'Prevention',
'Response',
'Recovery',
'Dirty Bomb',
'Domestic nuclear detection',
'Emergency management',
'Emergency response',
'First responder',
'Homeland security',
'Maritime domain awareness',
'National preparedness initiative',
'Militia',
'Shooting',
'Shots fired',
'Evacuation',
'Deaths',
'Hostage',
'Explosion',
'Police',
'Disaster medical assistance teeam (DMAT)',
'Organized crime',
'Gangs',
'National security',
'State of emergency',
'Security',
'Breach',
'Threat',
'Standoff',
'SWAT',
'Screening',
'Lockdown',
'Bomb ',
'Crash',
'Looting',
'Riot',
'Emergency Landing',
'Pipe bomb',
'Incident',
'Facility',
'Hazmat',
'Nuclear',
'Chemical spill',
'Suspicious package',
'Suspicious device',
'Toxic',
'National Laboratory',
'Nuclear facility',
'Nuclear threat',
'Cloud',
'Plume',
'Radiation',
'Radioactive',
'Leak',
'Biological infection',
'Chemical',
'Chemical burn',
'Biological',
'Epidemic',
'Hazardous',
'Hazardous material incident',
'Industrial spill',
'Infection',
'Powder',
'Gas',
'Spillover',
'Anthrax',
'Blister agent',
'Chemical agent',
'Exposure',
'Burn',
'Nerve agent',
'Ricin',
'Sarin',
'North Korea',
'Outbreak',
'Contamination',
'Exposure',
'Virus',
'Evacuation',
'Bacteria',
'Recall',
'Ebola',
'Food poisoning',
'Foot and Mouth',
'H5N1',
'Avian',
'Flu',
'Salmonella',
'Small Pox',
'Plague',
'Human to human',
'Human to Animal',
'Influenza',
'Center for Disease Control',
'Drug administration',
'Public health',
'Toxic',
'Agro terror',
'Tuberculosis',
'Agriculture',
'Listeria',
'Symptoms',
'Mutation',
'Resistant',
'Antiviral',
'Wave',
'Pandemic',
'Infection',
'Water/air borne',
'Sick',
'Swine',
'Pork',
'Strain',
'Quarantine',
'H1N1',
'Vaccine',
'Tamiflu',
'Norvo Virus',
'Epidemic',
'World Health Organization',
'Viral Hemorrhagic Fever',
'E. Coli',
'Infrastructure security',
'Airport',
'CIKR',
'AMTRAK',
'Collapse',
'Computer Infrastructure',
'Communications infrastructure',
'Telecommunications',
'Critical Infrastructure',
'National infrastucture',
'Metro',
'WMATA',
'Airplane',
'Chemical fire',
'Subway',
'BART',
'MARTA',
'Port Authority',
'NBIC',
'Transportation security',
'Grid',
'Power',
'Smart',
'Body scanner',
'Electric',
'Failure or outage',
'Black out',
'Brown out',
'Port',
'Dock',
'Bridge',
'Cancelled',
'Delays',
'Service disruption',
'Power lines',
'Drug cartel',
'Violence',
'Gang',
'Drug',
'Narcotics',
'Cocaine',
'Marijuana',
'Heroin',
'Border',
'Mexico',
'Cartel',
'Southwest',
'Juarez',
'Sinaloa',
'Tijuana',
'Torreon',
'Yuma',
'Tueson',
'Decapitated',
'U.S. Consulate',
'Consular',
'El Paso',
'Fort Hancock',
'San Diego',
'Ciudad Juarez',
'Nogales',
'Sonora',
'Colombia',
'Mara salvatrucha',
'MS13 or MS-13',
'Drug war',
'Mexican army',
'Methamphetamine',
'Cartel de Golfo',
'Gulf Cartel',
'La Familia',
'Reynosa',
'Nuevo Leon',
'Narcos',
'Narco banners',
'Los Zetos',
'Shootout',
'Execution',
'Gunfight',
'Trafficking',
'Kidnap',
'Calderon',
'Reyosa',
'Bust',
'Tamaulipas',
'Meth Lab',
'Drug trade',
'Illegal immigrants',
'Smuggling',
'Matamoros',
'Michoacana',
'Guzman',
'Arellano-Felix',
'Beltran-Leyva',
'Barrio Azteca',
'Artistic Assassins',
'Mexicles',
'New Federation',
'Terrorism',
'Al Qaeda',
'Terror',
'Attack',
'Iraq',
'Afghanistan',
'Iran',
'Pakistan',
'Agro',
'Environmental terrorist',
'Eco terrorism',
'Conventional weapon',
'Target',
'Weapons grade',
'Dirty Bomb',
'Enriched',
'Nuclear',
'Chemical weapon',
'Biological weapon',
'Ammonium nitrate',
'Improvised explosive device',
'IED',
'Abu Sayyaf',
'Hamas',
'FARC',
'IRA',
'ETA',
'Basque Separatists',
'Hezbollah',
'Tamil Tigers',
'PLF',
'PLO',
'Car bomb',
'Jihad',
'Taliban',
'Weapons cache',
'Suicide bomber',
'Suicide attack',
'Suspicious substance',
'AQAP',
'AQIM',
'TTP',
'Yemen',
'Pirates',
'Extremism',
'Somalia',
'Nigeria',
'Radicals',
'Al-Shabaab',
'Home grown',
'Plot',
'Nationalist',
'Recruitment',
'Fundamentalism',
'Islamist',
'Emergency',
'Hurricane',
'Tornado',
'Twister',
'Tsunami',
'Earthquake',
'Tremor',
'Flood',
'Storm',
'Crest',
'Temblor',
'Extreme weather',
'Forest fire',
'Brush fire',
'Ice',
'Stranded/Stuck',
'Help',
'Hail',
'Wildfire',
'Tsunami Warning Center',
'Magnitude',
'Avalanche',
'Typhoon',
'Shelter-in-ppace',
'Disaster',
'Snow',
'Blizzard',
'Sleet',
'Mud slide or mudslide',
'Erosion',
'Power outage',
'Brown out',
'Warning',
'Watch',
'Lightening',
'Aid',
'Relief',
'Closure',
'Interstate',
'Burst',
'Emergency Broadcast System',
'Cyber security',
'Botnet',
'DDOS',
'Denial of service',
'Malware',
'Virus',
'Trojan',
'Keylogger',
'Cyber Command',
'2600',
'Spammer',
'Phishing',
'Rootkit',
'Phreaking',
'Cain and abel',
'Brute forcing',
'Mysql injection',
'Cyber attack',
'Cyber terror',
'Hacker',
'China',
'Conflicker',
'Worm',
'Scammers'])
  